### ISSUE TITLE
pasto in shello.html.template ?

### ISSUE THREAD

**Issue by KelleyCook** [syncsynchalt/illustrated-dtls#1]
First of all this whole demonstration is really cool.

Anyhow on line 105 of generate/index-02-shello.html.template

`<li><xtt>%1 %2 %3</xtt> - %nnn1 bytes of client hello data is in this handshake record.`

Shouldn't that be "server hello" instead of "client hello" ?

**Comment by syncsynchalt** [comment]
Yep, copy paste error, good catch. Fixing now.
